const POST_ADD_IMAGES = "POST_ADD_IMAGES"
const SET_ADD_IMAGES = "SET_ADD_IMAGES"

const SET_DELETE_IMAGES = "SET_DELETE_IMAGES"
const POST_DELETE_IMAGES = "POST_DELETE_IMAGES"

export {
    POST_ADD_IMAGES,
    SET_ADD_IMAGES,

    SET_DELETE_IMAGES,
    POST_DELETE_IMAGES
}